### PR TITLE
Update sdk to 8.2

### PR DESCRIPTION
**Pull request by rajyraman**
1. Nuget for CRM SDKs
2. Refer Dynamics 365 SDKs

### CODE REVIEW

**Comment by kenakamu** [comment]
I could compile but I couldn't load the lpx. Could you do that?

**Comment by rajyraman** [comment]
I had to copy Microsoft.Xrm.Sdk.dll v7.1.0 to the same folder as LinqPad. Does that work for you?

**Comment by rajyraman** [comment]
Is there any way to get rid of this dependency to Microsoft.Xrm.Client as there is no 8.0 version of it? I just want to use Microsoft.Xrm.Tooling, but I am unable to figure out a way to make CrmSvcUtil not depend on Microsoft.Xrm.Client.

**Comment by rajyraman** [comment]
I figured out a way to do this little differently using @daryllabar CrmSvcUtil extension. I will submit another PR soon for that, if you are OK with adding this assembly as a dependency.

**Comment by daryllabar** [comment]
@rajyraman not that I have any issues with you using the EBG extensions, feel free to do so, but I do question why you need to use them to not have a dependency on Microsoft.Xrm.Client.

**Comment by rajyraman** [comment]
* I have to copy Microsoft.Xrm.Sdk.dll v7 to LINQPad executable folder to get this working without EBG
* Using EBG gives me greater control on what to generate.
* I can write queries like this
image

This is because I can generate the optionsets as well and use them right in my query, instead of fiddling around with formatted values.

The sad thing is I still need Microsoft.Xrm.Client.dll and Microsoft.Xrm.Client.CodeGeneration.dll during the code generation process, even though the generated code does not need it.

**Comment by daryllabar** [comment]
With the right settings, you could also do `a.TypeEnum == workflow_type` (without the casting)

**Comment by daryllabar** [comment]
The complied version I gave you shouldn't need those other dlls.

**Comment by rajyraman** [comment]
Got it. Much more convenient. Getting some error about duplicate enums when I try to generate for crm online. Will have to troubleshoot this.

image

**Pull request merged**
